// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_s0VVMhH0rRxs4vE8Ceb3_aJpa1TEQ3A',
    appId: '1:752341322023:web:5630322cd45e6877214102',
    messagingSenderId: '752341322023',
    projectId: 'gallery-af25c',
    authDomain: 'gallery-af25c.firebaseapp.com',
    storageBucket: 'gallery-af25c.appspot.com',
    measurementId: 'G-DBHEQP4BYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpMeijNWhLEuMxeRuzlCAGF4gbdFMpz_Q',
    appId: '1:752341322023:android:0cea0553576f93fb214102',
    messagingSenderId: '752341322023',
    projectId: 'gallery-af25c',
    storageBucket: 'gallery-af25c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpbOeh26rgkeGV0bjSG7cv1Dv_yZSDRRY',
    appId: '1:752341322023:ios:95624275f3e21a5b214102',
    messagingSenderId: '752341322023',
    projectId: 'gallery-af25c',
    storageBucket: 'gallery-af25c.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpbOeh26rgkeGV0bjSG7cv1Dv_yZSDRRY',
    appId: '1:752341322023:ios:95624275f3e21a5b214102',
    messagingSenderId: '752341322023',
    projectId: 'gallery-af25c',
    storageBucket: 'gallery-af25c.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );
}
